CREATE TABLE CONTROLTABLE_METADATA (
    TABLE_ID IDENTITY,
    TABLE_NAME VARCHAR(26),
    TABLE_TYPE CHAR(1),
    TABLE_VERSION VARCHAR(26),
    TABLE_HASH VARCHAR(2000),
    LAST_UPDATED TIMESTAMP
);